---
title: "Open Access Lab"
lang: de
author: 
  - name: Katharina Böhmer
    email: katharina.boehmer@unibe.ch
    orcid: 0009-0003-7269-6780
    affiliation: Universität Bern
  - name: Alessandra Fedrigo
    email: alessandra.fedrigo@unibe.ch
    orcid: 0009-0005-0968-7376
    affiliation: Universität Bern
categories: [Dienstleistungen]
other-links:
    - text: "English version"
      icon: globe
      href: ./../
---

## Herzlich willkommen beim OA Lab!

Wir bieten Beratung und Unterstützung für Wissenschaftler:innen, die unabhängig von kommerziellen Verlagen im Diamond Open Access (DOA) publizieren möchten: als Herausgeber:innen, Redaktor:innen oder Autor:innen von wissenschaftlichen Zeitschriften.

::: {.btn-group .d-flex .justify-content-center role="group" aria-label="Navigation für Zielgruppen"}
<a href="#für-herausgeberinnen" class="btn btn-outline-primary">Für Herausgeber:innen</a> <a href="#für-redaktorinnen" class="btn btn-outline-primary">Für Redaktor:innen</a> <a href="#für-autorinnen" class="btn btn-outline-primary">Für Autor:innen</a>
:::

## Für Herausgeber:innen

Gemeinsam mit Ihnen entwickeln wir:

-   neue OA-Journals
-   innovative Features für Ihre OA-Zeitschrift
-   Strategien zur Weiterentwicklung von bestehenden OA-Zeitschriften

Wir unterstützen Sie bei der:

-   Wahl von Formaten (HTML, PDF, XML), Veröffentlichungsplattformen (z. B. [OJS](https://pkp.sfu.ca/software/ojs/)), Hosting-Lösungen und Software
-   Transformation von bestehenden Print- oder Online-Journals zu OA/DOA (Flipping)
-   Aufnahme Ihrer OA-Zeitschrift in relevante Datenbanken und metrikbasierte Indizes (z. B. [DOAJ](https://doaj.org/), [Scopus](https://www.scopus.com/sources.uri?RN_AG_Sourced_400000654), [Web of Science Core Collection](https://mjl.clarivate.com/home), [EBSCO](https://www.ebsco.com/), [ERIH PLUS](https://kanalregister.hkdir.no/publiseringskanaler/erihplus/), [WorldCat](https://search.worldcat.org/de) etc.)
-   Entscheidung für geeignete OA-Lizenzen ([Creative Commons](https://creativecommons.org/share-your-work/cclicenses/))

Bei Fragen zu:

-   [Finanzierungsmöglichkeiten für Open-Access-Publikationen](https://www.ub.unibe.ch/service/open_science/open_access/index_ger.html#pane967852)
-   [Open-Access-Vorgaben von Forschungsförderinstitutionen](https://www.ub.unibe.ch/service/open_science/open_access/index_ger.html#pane1224714) (SNF)

wenden Sie sich an das Open-Science-Team der Universitätsbibliothek Bern UB: [openaccess\@ub.unibe.ch](mailto:openaccess@ub.unibe.ch)

## Für Redaktor:innen

Wir teilen unsere Expertise zu folgenden Themen:

-   Konzipierung des OA-Zeitschriftenworkflows
-   Redaktionsprozess: Richtlinien für Peer-Review, Lektorat, Stylesheet
-   Produktionsprozess: Formatierung, Satz, Fahnenkorrektur, Publikation
-   Best Practices: Workflow in OJS, Bildmanagement (Bildrechte und Bildbearbeitung)
-   Kommunikation mit Autor:innen und Editorial Board, Zeitmanagement
-   Plagiatsprüfung: Software und Umgang mit Plagiaten
-   Marketingstrategien (Social Media)

Wir bieten:

-   regelmässige Beratung und Schulungen für Redaktionsteams von OA-Journals
-   Hilfe bei der Optimierung von redaktionellen Workflows

Bei Fragen zu:

-   technischer Infrastruktur für scholar-led Open-Access-Zeitschriftenprojekten wie [BOP Serials](https://bop.unibe.ch/), [Open Journal Systems](https://pkp.sfu.ca/ojs/) (OJS), [SciFlow Publish](https://sciflow.net/de/sciflow-publish) und [Identifikatoren](https://www.ub.unibe.ch/service/open_science/identifikatoren/index_ger.html#pane583366) (DOI, ISBN, ISSN, GND)

wenden Sie sich an das Open-Science-Team der Universitätsbibliothek Bern UB: [openaccess\@ub.unibe.ch](mailto:openaccess@ub.unibe.ch)

## Für Autor:innen

Wir beraten Sie zu den Themen:

-   Bildmanagement (Bildrechte und Bildbearbeitung)
-   Kommunikation mit Museen, Bibliotheken, Archiven etc.
-   Kommunikation mit OA-Zeitschriften-Redaktionen
-   rechtliche Fragen (Urheberrecht)

Wir geben Tipps zur:

-   innovativen Aufbereitung von Bildmaterial
-   Einbettung von multimedialen Features in Texte (Video, Audio etc.)

Bei Fragen zu:

-   [Finanzierungsmöglichkeiten für Open-Access-Publikationen](https://www.ub.unibe.ch/service/open_science/open_access/index_ger.html#pane967852)
-   [Open-Access-Vorgaben von Forschungsförderinstitutionen](https://www.ub.unibe.ch/service/open_science/open_access/index_ger.html#pane1224714)
-   [Article Processing Charges (APC) und Book Processing Charges (BPC)](https://www.ub.unibe.ch/service/open_science/dienstleistungen/index_ger.html#collapse_pane780347)

wenden Sie sich an das Open-Science-Team der UB Bern: [openaccess\@ub.unibe.ch](mailto:openaccess@ub.unibe.ch)

## Wer wir sind

Das OA Lab ist eine Dienstleistung der Digital Humanities an der Universität Bern. Katharina Böhmer (Leitung) und Alessandra Fedrigo (Mitarbeit) haben als Redaktorinnen die erfolgreiche kunsthistorische Diamond OA-Zeitschrift [*21: Inquiries into Art, History, and the Visual*](https://21-inquiries.eu/) mit aufgebaut, sind Expertinnen im Bereich des OA-Publizierens von wissenschaftlichen Fachzeitschriften und spezialisiert auf digitales Bildmanagement. Ihre fundierte redaktionelle Expertise und ihre praktische Erfahrung geben sie gerne an Interessierte weiter.

Wir freuen uns auf Ihre Kontaktaufnahme!

**Kontakt:**\
[Katharina Böhmer](https://www.dh.unibe.ch/ueber_uns/personen/ma_boehmer_katharina/index_ger.html)\
[Alessandra Fedrigo](https://www.dh.unibe.ch/ueber_uns/personen/fedrigo_alessandra/index_ger.html)\
[oa-lab.dh\@unibe.ch](mailto:oa-lab.dh@unibe.ch)